#!/bin/bash

# remove temporary files; they tend to grow
rm -rf  /var/gerrit/tmp/*

# backup selected directories and files in /var/gerrit; name it 'gerrit'
cd /
/tar-backup gerrit /var/gerrit review_site
