#!/bin/bash

# remove index and temporary files;
# - index causes gerrit to break after restore
# - temporary files tend to grow
rm -rf /var/gerrit/index/* /var/gerrit/tmp/*

# backup selected directories and files in /var/gerrit; name it 'gerrit'
cd /
/tar-backup gerrit /var/gerrit review_site
