#!/bin/bash

# remove temporary files; they tend to grow
rm -rf /var/gerrit/tmp/*

# restore backup in directory /restore to directory /var/gerrit
# name of archive is gerrit
cd /
/tar-restore /restore /var/gerrit gerrit
